

version: "3.9"

services:
  client:
    image: safecycle-client
    build: 
      context: .
      dockerfile: ./client/safecycle-client/Dockerfile

    ports:
      - "8080:80"
  server:
    image: safecycle-server
    build: 
      context: .
      dockerfile: ./server/safecycle_server/Dockerfile
    ports:
      - "8000:8000"