version: "3.9"

services:

  safecycle-server:
    # build: ./server/safecycle_server/Dockerfile
    image: safecycle-server
    container_name: safecycle-server
    ports:
      - "8080:8080"

  safecycle-client:
    # build: ./client/safecycle-client/Dockerfile
    image: safecycle-client
    container_name: safecycle-client
    ports:
      - "4200:80"
    links:
      - safecycle-server

networks:
  default:
    name: nginxproxymanager_default
    external: true