

version: "3.9"

services:
  django:
    image: safecycle-server
    # build: ./server/safecycle_server
    ports:
      - "8080:8000"
  angular:
    image: safecycle-client
    # build: ./client/safecycle-client
    ports:
      - "8081:8000"